// <auto-generated />
using System;
using CloudMigrate.Business.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudMigrate.Business.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260621211119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CloudMigrate.DomainObjects.DBOs.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendedServicesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RisksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoadmapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeoffsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });
#pragma warning restore 612, 618
        }
    }
}
